name: Anticheat
version: '1.0-SNAPSHOT'
main: org.example.azheng.anticheat.Anticheat
api-version: '1.8'
depend:
  - packetevents
commands:
  ping:
    description: View a player's ping
    usage: /ping <player>
  reload:
    description: Reload the configuration files
    usage: /reload